export type Product = { id:string; slug:string; name:string; description:string; price:number; currency:'INR'; priceNote?:string; availableColours:string[]; customisable:boolean; customisationOptions:string[]; images:string[]; video?:string; category:string; featured:boolean; inventory:number };
export const products: Product[] = [
 {id:'pitti',slug:'pitti',name:'Pitti',price:250,currency:'INR',description:'A traditional wedding face-pack/ritual preparation used as part of pre-wedding celebrations for the bride and groom.',availableColours:[],customisable:false,customisationOptions:[],images:['/products/pitti/hero.jpg'],category:'Wedding rituals',featured:true,inventory:20},
 {id:'bajot',slug:'bajot',name:'Bajot',price:2500,currency:'INR',description:'A traditional low ceremonial table or platform used to place the pooja thali and other items during wedding rituals and ceremonies.',availableColours:[],customisable:false,customisationOptions:[],images:['/products/bajot/hero.jpg'],category:'Wedding rituals',featured:true,inventory:12},
 {id:'mala',slug:'mala',name:'Mala',price:5200,currency:'INR',priceNote:'Price is for a pair of 2.',description:'A pair of wedding garlands traditionally exchanged by the bride and groom during the varmala or jaimala ceremony.',availableColours:[],customisable:false,customisationOptions:[],images:['/products/mala/hero.jpg'],category:'Varmala',featured:true,inventory:8},
 {id:'topi',slug:'topi',name:'Topi',price:300,currency:'INR',description:"A traditional groom's wedding headpiece worn as part of his wedding attire.",availableColours:[],customisable:false,customisationOptions:[],images:['/products/topi/hero.jpg'],category:'Wedding attire',featured:true,inventory:20},
 {id:'toran',slug:'toran',name:'Toran',price:1100,currency:'INR',description:'A decorative wedding entrance hanging that adorns the doorway or entrance and welcomes guests and the arriving baraat. Torans are traditionally associated with auspicious occasions and wedding entrances.',availableColours:[],customisable:false,customisationOptions:[],images:['/products/toran/hero.jpg'],category:'Entrance decor',featured:true,inventory:10},
];
export const getProduct=(slug:string)=>products.find(p=>p.slug===slug);
export const formatPrice=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
